added full text description in config
PolicyEngine/policyengine-taxsim pull request #111
Opened 2024-11-18 14:43 UTC by noman404

added full text description in config
Resolves #53

2024-11-26 19:31 UTC, PavelMakarchuk requested changes
Some comments on the inputs - lmk if those make sense

2024-11-26 19:31 UTC, PavelMakarchuk commented on policyengine_taxsim/config/variable_mappings.yaml
>    v29:
Same as V17:
should be 2 outputs:

We were able to generate an output previously - not sure which variable it was - will reach out to Martin

`taxsim_tfica` - this is the taxpayer share

2024-11-26 19:31 UTC, PavelMakarchuk commented on policyengine_taxsim/config/variable_mappings.yaml
>      variable: not_implemented_in_pe
We have state exemptions - just not in one variable (naming varies) - is this a change in the US package that needs to happen?

2024-11-26 19:31 UTC, PavelMakarchuk commented on policyengine_taxsim/config/variable_mappings.yaml
>      variable: not_implemented_in_pe
generally using 'state_exemptions' should produce a valid result in ~80% of the states

2024-11-26 19:31 UTC, PavelMakarchuk commented on policyengine_taxsim/config/variable_mappings.yaml
>      variable: not_implemented_in_pe
we can generally use 'state_cdcc' with some exemptions

2024-11-26 19:31 UTC, PavelMakarchuk commented on policyengine_taxsim/config/variable_mappings.yaml
> +    text_description: "39. EIC \n Energy|Fuel Credit \n Child Tax Credit"
EIC: 'state_eitc' - same limitations as cdcc

Child Tax credit: 'state_ctc' same limitations as cdcc

2024-11-26 19:31 UTC, PavelMakarchuk commented on policyengine_taxsim/config/variable_mappings.yaml
> +    text_description: "40. Total Credits"
this should be a sum of
'state_non_refundable_credit'
and 
'state_refundable_credits'

2024-11-26 19:31 UTC, PavelMakarchuk commented on policyengine_taxsim/config/variable_mappings.yaml
>      variable: self_employment_income
this should be the `qualified_business_income_deduction`

2024-11-26 19:31 UTC, PavelMakarchuk commented on policyengine_taxsim/config/variable_mappings.yaml
> +    text_description: "Medicare tax on Unearned Income"
v44 is medicare right?

2024-11-26 19:31 UTC, PavelMakarchuk commented on policyengine_taxsim/config/variable_mappings.yaml
> +    text_description: "Medicare tax on Unearned Income"
this is net investment income tax

2024-11-26 19:31 UTC, PavelMakarchuk commented on policyengine_taxsim/config/variable_mappings.yaml
> +    text_description: "Not available in taxsim full text description"
medicare

2024-12-06 23:33 UTC, MaxGhenis commented
what's the status on this pr?

2024-12-10 13:50 UTC, noman404 commented on policyengine_taxsim/config/variable_mappings.yaml
> +    variables:
updated

2024-12-10 13:55 UTC, noman404 commented on policyengine_taxsim/config/variable_mappings.yaml
> +      - self_employment_income:
planning this part to restructure after confirming with dan for the other possible input mapping, currently there are some variables which does not have any match, like these 

```
      - rental_income:
      - w2_wages_from_qualified_business:
      - business_is_sstb:
      - business_is_qualified:
      - social_security:
```

2024-12-11 03:11 UTC, noman404 commented on policyengine_taxsim/config/variable_mappings.yaml
> +      - self_employment_income:
comment from Dan

interest income for 
 - rental_income:
 - w2_wages_from_qualified_business:
 - business_is_sstb:
 - business_is_qualified
 
and gssi for
 - social_security:

2024-12-13 13:27 UTC, MaxGhenis commented
Merging as we have issues for remaining tasks

2024-12-13 13:27 UTC, merged